config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

username_regex = /([^\/]*)/
html_only = lambda { |req| req.format.nil? || req.format.html? }

Rails.application.routes.draw do

  mount StripeEvent::Engine, at: '/stripe-webhooks' # provide a custom path

  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
    mount PgHero::Engine, at: 'pghero', as: :pghero
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations',
                authorized_applications: 'oauth/authorized_applications',
                tokens: 'oauth/tokens'
  end

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/change-password', to: redirect('/auth/edit')
  get '.well-known/keybase-proof-config', to: 'well_known/keybase_proof_config#show'

  get 'manifest', to: 'manifests#show', defaults: { format: 'json' }
  get 'intent', to: 'intents#show'

  devise_scope :user do
    get '/invite/:invite_code', to: 'auth/registrations#new', as: :public_invite
    match '/auth/finish_signup' => 'auth/confirmations#finish_signup', via: [:get, :patch], as: :finish_signup
  end

  devise_for :users, path: 'auth', controllers: {
    omniauth_callbacks: 'auth/omniauth_callbacks',
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations',
  }

  get '/users/:username', to: redirect('/%{username}'), constraints: html_only, username: username_regex
  get '/users/:username/followers', to: redirect('/%{username}/followers'), constraints: html_only, username: username_regex
  get '/users/:username/following', to: redirect('/%{username}/following'), constraints: html_only, username: username_regex
  get '/users/:username/statuses/:id', to: redirect('/%{username}/posts/%{id}'), constraints: html_only, username: username_regex

  get '/authorize_follow', to: redirect { |_, request| "/authorize_interaction?#{request.params.to_query}" }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show] do
      member do
        get :embed
      end
    end

    # get :remote_follow,  to: 'remote_follow#new'
    # post :remote_follow, to: 'remote_follow#create'

    resources :statuses, only: [:show] do
      member do
        get :activity
        get :embed
        get :replies
      end
    end

    resources :followers, only: [:index], controller: :follower_accounts
    resources :following, only: [:index], controller: :following_accounts
    resource :follow, only: [:create], controller: :account_follow
    resource :unfollow, only: [:create], controller: :account_unfollow

    # resource :outbox, only: [:show], module: :activitypub
    # resource :inbox, only: [:create], module: :activitypub
    # resources :collections, only: [:show], module: :activitypub
  end

  # resource :inbox, only: [:create], module: :activitypub

  get  '/interact/:id', to: 'remote_interaction#new', as: :remote_interaction
  post '/interact/:id', to: 'remote_interaction#create'

  namespace :settings do
    resources :memberships, only: [:index] do
      collection do
        post :cancel
        post :change_membership
        post :create_checkout_session
      end
    end
    resource :profile, only: [:show, :update]
    resource :preferences, only: [:show, :update]
    resource :notifications, only: [:show, :update]
    # resource :import, only: [:show, :create]

    namespace :billing do
      get :upgrade, to: 'upgrade#index', as: :upgrade
      get :transactions, to: 'transactions#index', as: :transactions
      post '/btcpay-notification', to: 'upgrade#btcpay_notification', as: :btcpay_notification
    end

    resources :promotions, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :expenses, only: [:index, :new, :create, :edit, :update, :destroy]

    namespace :verifications do
      get :moderation, to: 'moderation#index', as: :moderation
      get 'moderation/:id/approve', to: 'moderation#approve', as: :approve
      get 'moderation/:id/reject', to: 'moderation#reject', as: :reject

      resources :requests, only: [:index, :create]
      post 'requests/sendcode', to: 'requests#send_code', as: :sendcode
      post 'requests/verifycode', to: 'requests#verify_code', as: :verifycode
    end

    resource :export, only: [:show, :create]
    namespace :exports, constraints: { format: :csv } do
      resources :follows, only: :index, controller: :following_accounts
      resources :blocks, only: :index, controller: :blocked_accounts
      resources :mutes, only: :index, controller: :muted_accounts
      resources :lists, only: :index, controller: :lists
      resources :domain_blocks, only: :index, controller: :blocked_domains
    end

    resource :two_factor_authentication, only: [:show, :create, :destroy]
    namespace :two_factor_authentication do
      resources :recovery_codes, only: [:create]
      resource :confirmation, only: [:new, :create]
    end

    resources :identity_proofs, only: [:index, :show, :new, :create, :update]

    resources :applications, except: [:edit] do
      member do
        post :regenerate
      end
    end

    resource :delete, only: [:show, :destroy]
    # resource :migration, only: [:show, :update]

    resources :sessions, only: [:destroy]
    resources :scheduled_statuses, only: [:index, :destroy]
  end

  resources :media, only: [:show] do
    get :player
  end

  resources :emojis, only: [:show]
  # resources :invites, only: [:index, :create, :destroy]
  resources :filters, except: [:show]
  # resource :relationships, only: [:show, :update]

  get '/public', to: redirect('/home'), as: :public_timeline # homehack
  get '/media_proxy/:id/(*any)', to: 'media_proxy#show', as: :media_proxy

  # Remote follow
  # resource :remote_unfollow, only: [:create]
  # resource :authorize_interaction, only: [:show, :create]
  # resource :share, only: [:show, :create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :subscriptions, only: [:index]
    resources :domain_blocks, only: [:new, :create, :show, :destroy]
    resources :email_domain_blocks, only: [:index, :new, :create, :destroy]
    resources :action_logs, only: [:index]
    resources :warning_presets, except: [:new]
    resource :settings, only: [:edit, :update]

    resources :invites, only: [:index, :create, :destroy] do
      collection do
        post :deactivate_all
      end
    end

    resources :relays, only: [:index, :new, :create, :destroy] do
      member do
        post :enable
        post :disable
      end
    end

    resources :instances, only: [:index, :show], constraints: { id: /[^\/]+/ }

    resources :reports, only: [:index, :show] do
      member do
        post :assign_to_self
        post :unassign
        post :reopen
        post :resolve
      end

      resources :reported_statuses, only: [:create]
    end

    resources :report_notes, only: [:create, :destroy]

    resources :accounts, only: [:index, :show, :edit, :update] do
      member do
        post :subscribe
        post :unsubscribe
        post :enable
        post :unsilence
        post :unsuspend
        post :redownload
        post :remove_avatar
        post :remove_header
        post :memorialize
        post :approve
        post :reject
        post :verify
        post :unverify
        post :add_proplus_badge
        post :remove_proplus_badge
        post :add_expert_badge
        post :remove_expert_badge
        get :edit_pro
        put :save_pro
      end

      resource :change_email, only: [:show, :update]
      resource :reset, only: [:create]
      resource :action, only: [:new, :create], controller: 'account_actions'
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :followers, only: [:index]

      resource :confirmation, only: [:create] do
        collection do
          post :resend
        end
      end

      resource :role do
        member do
          post :promote
          post :demote
        end
      end
    end

    resources :pending_accounts, only: [:index] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end

    resources :users, only: [] do
      resource :two_factor_authentication, only: [:destroy]
    end

    resources :custom_emojis, only: [:index, :new, :create, :update, :destroy] do
      member do
        post :copy
        post :enable
        post :disable
      end
    end

    resources :groups, only: [:index, :destroy] do
      member do
        post :enable_featured
        post :disable_featured
        post :enable_privated
        post :disable_privated
      end
    end

    resources :account_moderation_notes, only: [:create, :destroy]

    resources :tags, only: [:index] do
      member do
        post :hide
        post :unhide
      end
    end
  end

  get '/admin', to: redirect('/admin/dashboard', status: 302)

  namespace :api do
    # PubSubHubbub outgoing subscriptions
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # PubSubHubbub incoming subscriptions
    post '/push', to: 'push#update', as: :push

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # Identity proofs
    get :proofs, to: 'proofs#index'

    # JSON / REST API
    namespace :v1 do
      post '/ambassadors/webhook', to: 'ambassadors#index'

app/controllers/directories_controller.rb
# frozen_string_literal: true

class DirectoriesController < ApplicationController
  layout 'public'

  before_action :check_enabled
  before_action :set_instance_presenter
  before_action :set_tag, only: :show
  before_action :set_tags
  before_action :set_accounts

  def index
    render :index
  end

  def show
    render :index
  end

  private

  def check_enabled
    return not_found unless Setting.profile_directory
  end

  def set_tag
    @tag = Tag.discoverable.find_by!(name: params[:id].downcase)
  end

  def set_tags
    @tags = Tag.discoverable.limit(30).reject { |tag| tag.cached_sample_accounts.empty? }
  end

  def set_accounts
    @accounts = Account.discoverable.by_recent_status.page(params[:page]).per(40).tap do |query|
      query.merge!(Account.tagged_with(@tag.id)) if @tag
    end
  end

  def set_instance_presenter
    @instance_presenter = InstancePresenter.new
  end
end

app/views/directories/index.html.haml
- content_for :page_title do
  = t('directories.explore_gabsocial', title: site_title)

- content_for :header_tags do
  %meta{ name: 'description', content: t('directories.explanation') }

  = opengraph 'og:site_name', t('about.hosted_on', domain: site_hostname)
  = opengraph 'og:type', 'website'
  = opengraph 'og:title', t('directories.explore_gabsocial', title: site_title)
  = opengraph 'og:description', t('directories.explanation')
  = opengraph 'og:image', File.join(root_url, 'android-chrome-192x192.png')

.page-header
  %h1= t('directories.explore_gabsocial', title: site_title)
  %p= t('directories.explanation')

.grid
  .column-0
    - if @accounts.empty?
      = nothing_here
    - else
      .directory
        %table.accounts-table
          %tbody
            - @accounts.each do |account|
              %tr
                %td= account_link_to account
                %td.accounts-table__count.optional
                  = number_to_human account.statuses_count, strip_insignificant_zeros: true
                  %small= t('accounts.posts', count: account.statuses_count).downcase
                %td.accounts-table__count.optional
                  = number_to_human account.followers_count, strip_insignificant_zeros: true
                  %small= t('accounts.followers', count: account.followers_count).downcase
                %td.accounts-table__count
                  - if account.last_status_at.present?
                    %time.time-ago{ datetime: account.last_status_at.iso8601, title: l(account.last_status_at) }= l account.last_status_at
                  - else
                    \-
                  %small= t('accounts.last_active')

      = paginate @accounts

  .column-1
    - if user_signed_in?
      .box-widget.notice-widget
        - if current_account.discoverable?
          - if current_account.followers_count < Account::MIN_FOLLOWERS_DISCOVERY
            %p= t('directories.enabled_but_waiting', min_followers: Account::MIN_FOLLOWERS_DISCOVERY)
          - else
            %p= t('directories.enabled')
        - else
          %p= t('directories.how_to_enable')

          = link_to settings_profile_path do
            = t('settings.edit_profile')
            = fa_icon 'chevron-right fw'

    - if @tags.empty? && !user_signed_in?
      .nothing-here
    - else
      - @tags.each do |tag|
        .directory__tag{ class: tag.id == @tag&.id ? 'active' : nil }
          = link_to explore_hashtag_path(tag) do
            %h4
              = fa_icon 'hashtag'
              = tag.name
              %small= t('directories.people', count: tag.accounts_count)

            .avatar-stack
              - tag.cached_sample_accounts.each do |account|
                = image_tag current_account&.user&.setting_auto_play_gif ? account.avatar_original_url : account.avatar_static_url, width: 48, height: 48, alt: '', class: 'account__avatar'